import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { WatchFaceSpec } from '../preview/watchface-model.js'
import { generateMonkeyCView } from '../preview/code-generator.js'

export interface ScaffoldOptions {
  projectDir: string
  appName: string
  clockType?: 'analog' | 'digital' | 'hybrid'
  theme?: string
  spec?: WatchFaceSpec
}

export async function scaffoldGarminProject(options: ScaffoldOptions): Promise<{ success: boolean; filesCreated: string[] }> {
  const root = options.projectDir
  const filesCreated: string[] = []

  // Ensure directories
  await fs.mkdir(path.join(root, 'source'), { recursive: true })
  await fs.mkdir(path.join(root, 'resources', 'layouts'), { recursive: true })
  await fs.mkdir(path.join(root, 'resources', 'strings'), { recursive: true })
  await fs.mkdir(path.join(root, 'resources', 'drawables'), { recursive: true })

  // 1. manifest.xml
  const uuid = 'a1b2c3d4-e5f6-7a8b-9c0d-' + Date.now().toString(16).padStart(12, '0')
  const manifestXml = `<?xml version="1.0"?>
<!-- This is a generated file. It is highly recommended that you DO NOT edit this file. -->
<iq:manifest version="3" xmlns:iq="http://www.garmin.com/xml/connectiq">
    <iq:application entry="GarminWatchFaceApp" id="${uuid}" launcherIcon="@Drawables.LauncherIcon" name="@Strings.AppName" type="watchface" minSdkVersion="4.0.0">
        <iq:products>
            <iq:product id="fenix7"/>
            <iq:product id="fenix7solar"/>
            <iq:product id="fenix7pro"/>
        </iq:products>
        <iq:permissions>
            <iq:uses-permission id="SensorHistory"/>
            <iq:uses-permission id="ActivityMonitor"/>
        </iq:permissions>
    </iq:application>
</iq:manifest>
`
  await fs.writeFile(path.join(root, 'manifest.xml'), manifestXml)
  filesCreated.push('manifest.xml')

  // 2. monkey.jungle
  const monkeyJungle = `project.manifest = manifest.xml
`
  await fs.writeFile(path.join(root, 'monkey.jungle'), monkeyJungle)
  filesCreated.push('monkey.jungle')

  // 3. resources/strings/strings.xml
  const stringsXml = `<strings>
    <string id="AppName">${options.appName}</string>
</strings>
`
  await fs.writeFile(path.join(root, 'resources', 'strings', 'strings.xml'), stringsXml)
  filesCreated.push('resources/strings/strings.xml')

  // 4. source/App.mc
  const appMc = `import Toybox.Application;
import Toybox.Lang;
import Toybox.WatchUi;

class GarminWatchFaceApp extends Application.AppBase {

    function initialize() {
        AppBase.initialize();
    }

    function onStart(state as Dictionary?) as Void {
    }

    function onStop(state as Dictionary?) as Void {
    }

    function getInitialView() as [Views] or [Views, InputDelegates] {
        return [ new GarminWatchFaceView() ];
    }
}

function getApp() as GarminWatchFaceApp {
    return Application.getApp() as GarminWatchFaceApp;
}
`
  await fs.writeFile(path.join(root, 'source', 'App.mc'), appMc)
  filesCreated.push('source/App.mc')

  // 5. source/View.mc (generate dynamically if spec is provided, or build default spec)
  let viewMc: string
  if (options.spec) {
    viewMc = generateMonkeyCView(options.spec)
  } else {
    const defaultSpec: WatchFaceSpec = {
      name: options.appName,
      theme: (options.theme as any) || 'sport',
      targetDevice: 'fenix7',
      backgroundColor: '#000000',
      dial: {
        showTicks: true,
        tickColor: '#555555',
        subTicks: false,
        showNumbers: false,
        numberColor: '#AAAAAA',
        radius: 120
      },
      clockType: options.clockType || 'digital',
      digitalClock: {
        x: 130,
        y: 105,
        font: 'NUMBER_HOT',
        color: '#FFFFFF',
        showSeconds: true,
        showAmPm: false
      },
      analogHands: options.clockType === 'analog' || options.clockType === 'hybrid' ? {
        hourColor: '#FFFFFF',
        minuteColor: '#00AAFF',
        secondColor: '#FF0000',
        hourLength: 55,
        minuteLength: 85,
        secondLength: 100,
        hourWidth: 4,
        minuteWidth: 3,
        secondWidth: 1,
        accentTail: true
      } : undefined,
      complications: [
        { id: 'bat', type: 'battery', position: { x: 130, y: 155 }, style: 'bar_progress', color: '#AAAAAA' },
        { id: 'step', type: 'steps', position: { x: 130, y: 180 }, style: 'arc_progress', color: '#00AAFF' }
      ]
    }
    viewMc = generateMonkeyCView(defaultSpec)
  }

  await fs.writeFile(path.join(root, 'source', 'View.mc'), viewMc)
  filesCreated.push('source/View.mc')

  return { success: true, filesCreated }
}
