import * as fs from 'node:fs/promises'
import * as path from 'node:path'

export interface ScaffoldOptions {
  projectDir: string
  appName: string
  clockType: 'analog' | 'digital' | 'hybrid'
  theme: string
}

export async function scaffoldGarminProject(options: ScaffoldOptions): Promise<{ success: boolean; filesCreated: string[] }> {
  const root = options.projectDir
  const filesCreated: string[] = []

  // Ensure directories
  await fs.mkdir(path.join(root, 'source'), { recursive: true })
  await fs.mkdir(path.join(root, 'resources', 'layouts'), { recursive: true })
  await fs.mkdir(path.join(root, 'resources', 'strings'), { recursive: true })
  await fs.mkdir(path.join(root, 'resources', 'drawables'), { recursive: true })

  // 1. manifest.xml
  const uuid = 'a1b2c3d4-e5f6-7a8b-9c0d-' + Date.now().toString(16).padStart(12, '0')
  const manifestXml = `<?xml version="1.0"?>
<!-- This is a generated file. It is highly recommended that you DO NOT edit this file. -->
<iq:manifest version="3" xmlns:iq="http://www.garmin.com/xml/connectiq">
    <iq:application entry="GarminWatchFaceApp" id="${uuid}" launcherIcon="@Drawables.LauncherIcon" name="@Strings.AppName" type="watchface" minSdkVersion="4.0.0">
        <iq:products>
            <iq:product id="fenix7"/>
            <iq:product id="fenix7solar"/>
            <iq:product id="fenix7pro"/>
        </iq:products>
        <iq:permissions>
            <iq:uses-permission id="SensorHistory"/>
            <iq:uses-permission id="ActivityMonitor"/>
        </iq:permissions>
    </iq:application>
</iq:manifest>
`
  await fs.writeFile(path.join(root, 'manifest.xml'), manifestXml)
  filesCreated.push('manifest.xml')

  // 2. monkey.jungle
  const monkeyJungle = `project.manifest = manifest.xml
`
  await fs.writeFile(path.join(root, 'monkey.jungle'), monkeyJungle)
  filesCreated.push('monkey.jungle')

  // 3. resources/strings/strings.xml
  const stringsXml = `<strings>
    <string id="AppName">${options.appName}</string>
</strings>
`
  await fs.writeFile(path.join(root, 'resources', 'strings', 'strings.xml'), stringsXml)
  filesCreated.push('resources/strings/strings.xml')

  // 4. source/App.mc
  const appMc = `import Toybox.Application;
import Toybox.Lang;
import Toybox.WatchUi;

class GarminWatchFaceApp extends Application.AppBase {

    function initialize() {
        AppBase.initialize();
    }

    function onStart(state as Dictionary?) as Void {
    }

    function onStop(state as Dictionary?) as Void {
    }

    function getInitialView() as [Views] or [Views, InputDelegates] {
        return [ new GarminWatchFaceView() ];
    }
}

function getApp() as GarminWatchFaceApp {
    return Application.getApp() as GarminWatchFaceApp;
}
`
  await fs.writeFile(path.join(root, 'source', 'App.mc'), appMc)
  filesCreated.push('source/App.mc')

  // 5. source/View.mc
  const viewMc = `import Toybox.Graphics;
import Toybox.Lang;
import Toybox.System;
import Toybox.WatchUi;
import Toybox.ActivityMonitor;
import Toybox.Time;
import Toybox.Time.Gregorian;

class GarminWatchFaceView extends WatchUi.WatchFace {

    private var _isSleep as Boolean = false;
    private var _screenCenter as Number = 130;

    function initialize() {
        WatchFace.initialize();
    }

    function onLayout(dc as Graphics.Dc) as Void {
        _screenCenter = dc.getWidth() / 2;
    }

    function onShow() as Void {
    }

    function onUpdate(dc as Graphics.Dc) as Void {
        // 1. Clear background
        dc.setColor(Graphics.COLOR_BLACK, Graphics.COLOR_BLACK);
        dc.clear();

        var width = dc.getWidth();
        var height = dc.getHeight();
        var cx = _screenCenter;
        var cy = _screenCenter;

        // 2. Draw Dial Ticks
        dc.setColor(Graphics.COLOR_DK_GRAY, Graphics.COLOR_TRANSPARENT);
        for (var i = 0; i < 60; i += 5) {
            var angleRad = (i * 6 * Math.PI) / 180.0;
            var r1 = 112;
            var r2 = 120;
            var x1 = cx + r1 * Math.sin(angleRad);
            var y1 = cy - r1 * Math.cos(angleRad);
            var x2 = cx + r2 * Math.sin(angleRad);
            var y2 = cy - r2 * Math.cos(angleRad);
            dc.drawLine(x1, y1, x2, y2);
        }

        // 3. Time
        var clockTime = System.getClockTime();
        var timeStr = Lang.format("$1$:$2$", [clockTime.hour.format("%02d"), clockTime.min.format("%02d")]);

        dc.setColor(Graphics.COLOR_WHITE, Graphics.COLOR_TRANSPARENT);
        dc.drawText(cx, cy - 25, Graphics.FONT_NUMBER_HOT, timeStr, Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);

        // 4. Battery & Heart Rate / Steps
        var stats = System.getSystemStats();
        var batPercent = stats.battery != null ? stats.battery.toNumber() : 100;
        var batColor = batPercent <= 20 ? Graphics.COLOR_RED : Graphics.COLOR_LT_GRAY;
        dc.setColor(batColor, Graphics.COLOR_TRANSPARENT);
        dc.drawText(cx, cy + 30, Graphics.FONT_TINY, batPercent.toString() + "%", Graphics.TEXT_JUSTIFY_CENTER);

        var info = ActivityMonitor.getInfo();
        var steps = (info != null && info.steps != null) ? info.steps : 0;
        dc.setColor(Graphics.COLOR_BLUE, Graphics.COLOR_TRANSPARENT);
        dc.drawText(cx, cy + 50, Graphics.FONT_XTINY, "STEPS: " + steps.toString(), Graphics.TEXT_JUSTIFY_CENTER);
    }

    function onHide() as Void {
    }

    function onExitSleep() as Void {
        _isSleep = false;
        WatchUi.requestUpdate();
    }

    function onEnterSleep() as Void {
        _isSleep = true;
        WatchUi.requestUpdate();
    }
}
`
  await fs.writeFile(path.join(root, 'source', 'View.mc'), viewMc)
  filesCreated.push('source/View.mc')

  return { success: true, filesCreated }
}
